FROM php:8.2-cli
WORKDIR /var/www/html
COPY . .
RUN apt-get update && apt-get install -y libzip-dev zip \
 && docker-php-ext-install pdo pdo_mysql zip \
 && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
 && composer install --no-dev --optimize-autoloader \
 && chown -R www-data:www-data /var/www/html
EXPOSE 8000
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
