apiVersion: apps/v1
kind: Deployment
metadata:
  name: aldous
  labels:
    app: aldous
    app.kubernetes.io/name: aldous
    app.kubernetes.io/instance: aldous
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aldous
  template:
    metadata:
      labels:
        app: aldous
        app.kubernetes.io/name: aldous
        app.kubernetes.io/instance: aldous
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: aldous
                topologyKey: kubernetes.io/hostname
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: aldous
      serviceAccountName: aldous
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: php
          image: localhost:5000/aldous:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
              ephemeral-storage: "100Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
              ephemeral-storage: "500Mi"
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: tmp
          emptyDir: {}

