apiVersion: apps/v1
kind: Deployment
metadata:
  name: aldous
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aldous
  template:
    metadata:
      labels:
        app: aldous
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: php
        image: localhost:5000/aldous:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        securityContext:
          runAsNonRoot: true
          runAsUser: 82
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: tmp
        emptyDir: {}
