apiVersion: v1
kind: LimitRange
metadata:
  name: aldous-limits
  namespace: default
spec:
  limits:
  - type: Container
    defaultRequest: { cpu: 50m, memory: 128Mi, ephemeral-storage: 256Mi }
    default:        { cpu: 200m, memory: 256Mi, ephemeral-storage: 1Gi }
    max:            { cpu: 1, memory: 2Gi, ephemeral-storage: 4Gi }
