apiVersion: v1
kind: LimitRange
metadata:
  name: aldous-limits
  namespace: default
spec:
  limits:
    - type: Container
      default:
        cpu: "500m"
        memory: "256Mi"
        ephemeral-storage: "500Mi"
      defaultRequest:
        cpu: "50m"
        memory: "64Mi"
        ephemeral-storage: "100Mi"
      max:
        cpu: "1"
        memory: "512Mi"
        ephemeral-storage: "1Gi"

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: aldous-quota
  namespace: default
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "2Gi"
    requests.ephemeral-storage: "4Gi"
    limits.cpu: "4"
    limits.memory: "4Gi"
    limits.ephemeral-storage: "4Gi"
    pods: "32"
    services: "32"
    secrets: "32"
    configmaps: "32"
