apiVersion: v1
kind: LimitRange
metadata:
  name: aldous-limits
  namespace: default
spec:
  limits:
    - type: Container
      default:
        cpu: "500m"
        memory: "256Mi"
        ephemeral-storage: "500Mi"
      defaultRequest:
        cpu: "50m"
        memory: "64Mi"
        ephemeral-storage: "100Mi"
      max:
        cpu: "1"
        memory: "512Mi"
        ephemeral-storage: "1Gi"

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: aldous-quota
  namespace: default
spec:
  hard:
    requests.cpu: "8"
    limits.cpu: "16"
    requests.memory: "12Gi"
    limits.memory: "24Gi"
    requests.ephemeral-storage: "16Gi"
    limits.ephemeral-storage: "64Gi"
    pods: "100"
    services: "64"
    secrets: "256"
    configmaps: "256"
