proxy: edge
hostname: auth.aldous.info
ingress:
  enabled: true
  ingressClassName: kong
  hostname: auth.aldous.info
  tls: true
  existingSecret: cloudflare-origin-cert
auth:
  adminUser: admin
  adminPassword: changeme
postgresql:
  enabled: false
externalDatabase:
  host: "pg-cluster-rw.default.svc.cluster.local"
  user: keycloak
  password: keycloak
  database: keycloak
cache:
  enabled: true
  type: redis
  redis:
    host: "redis-master.default.svc.cluster.local"
persistence:
  enabled: true
  size: 5Gi
  storageClass: ceph-rbd
extraEnv:
  - name: KC_SPI_STORAGE_S3_BUCKET
    value: keycloak-bucket
  - name: KC_SPI_STORAGE_S3_ENDPOINT
    value: "http://microk8s-hl.minio-operator.svc.cluster.local:9000"
  - name: KC_SPI_STORAGE_S3_ACCESSKEY
    valueFrom:
      secretKeyRef:
        name: microk8s-user-1
        key: CONSOLE_ACCESS_KEY
  - name: KC_SPI_STORAGE_S3_SECRETKEY
    valueFrom:
      secretKeyRef:
        name: microk8s-user-1
        key: CONSOLE_SECRET_KEY
