proxy: edge
hostname: auth.aldous.info
ingress:
  enabled: true
  ingressClassName: kong
  hostname: auth.aldous.info
  tls: true
  existingSecret: cloudflare-origin-cert
auth:
  adminUser: admin
  existingSecret: keycloak-admin
  existingSecretPasswordKey: admin-password
postgresql:
  enabled: false
externalDatabase:
  host: "pg-cluster-rw.default.svc.cluster.local"
  existingSecret: "pg-cluster-app"
  existingSecretUserKey: "username"
  existingSecretPasswordKey: "password"
  database: app
cache:
  enabled: true
  type: redis
  redis:
    host: "redis-master.default.svc.cluster.local"
persistence:
  enabled: true
  size: 5Gi
  storageClass: standard
readinessProbe:
  httpGet:
    path: /health/ready
    port: http
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
extraEnvVars:
  - name: KC_SPI_STORAGE_S3_BUCKET
    value: keycloak-bucket
  - name: KC_SPI_STORAGE_S3_ENDPOINT
    value: "http://minio.default.svc.cluster.local:9000"
  - name: KC_SPI_STORAGE_S3_ACCESSKEY
    valueFrom:
      secretKeyRef:
        name: minio-root-credentials
        key: root-user
  - name: KC_SPI_STORAGE_S3_SECRETKEY
    valueFrom:
      secretKeyRef:
        name: minio-root-credentials
        key: root-password
  - name: KC_LOG_LEVEL
    value: "info,org.keycloak.protocol.oidc:debug,org.keycloak.authentication:debug,org.keycloak.events:debug,org.keycloak.services:debug"

