mode: standalone
auth:
  existingSecret: minio-root-credentials

persistence:
  enabled: true
  storageClass: standard
  size: 10Gi

service:
  type: ClusterIP
  port: 9000

consoleService:
  type: ClusterIP
  port: 9001

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 500m

buckets:
  - name: keycloak-bucket
    policy: none
    purge: false
