tempo:
  structuredConfig:
    usage_report:
      reporting_enabled: false
    server:
      http_listen_port: 3200
      grpc_listen_port: 9095
    distributor:
      receivers:
        otlp:
          protocols:
            http: {}
            grpc: {}
    storage:
      trace:
        backend: local
        wal:
          path: /var/tempo/wal
        local:
          path: /var/tempo/blocks
    compactor:
      compaction:
        block_retention: 24h
  persistence:
    enabled: false   # emptyDir for /var/tempo
  extraVolumeMounts:
    - name: tempo-data
      mountPath: /var/tempo
  extraVolumes:
    - name: tempo-data
      emptyDir: {}

test:
  enabled: false
resources:
  limits: { cpu: 200m, memory: 256Mi }
  requests: { cpu: 50m, memory: 128Mi }
